services:
  # Main Flask API
  - type: web
    name: leadnest-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    plan: starter
    branch: main
    rootDir: ./backend-flask
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: leadnest-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: leadnest-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PUBLIC_BASE_URL
        value: https://leadnest-api.onrender.com
      - key: LOG_LEVEL
        value: INFO
      - key: CORS_ORIGINS
        value: https://leadnest.vercel.app,https://useleadnest.com
      - key: FLASK_ENV
        value: production
      # Twilio vars (you'll add these manually)
      - key: TWILIO_ACCOUNT_SID
        value: ""  # Add your Twilio Account SID
      - key: TWILIO_AUTH_TOKEN
        value: ""  # Add your Twilio Auth Token  
      - key: TWILIO_FROM
        value: ""  # Add your Twilio phone number

  # Background Worker
  - type: worker
    name: leadnest-worker
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    plan: starter
    branch: main
    rootDir: ./backend-flask
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: leadnest-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: leadnest-redis
          property: connectionString
      - key: JWT_SECRET
        sync: false  # Will inherit from web service

databases:
  - name: leadnest-db
    plan: starter

services:
  - type: redis
    name: leadnest-redis
    plan: starter
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: YELP_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
    domains:
      - leadnest-api.onrender.com
    
  # API Documentation Site
  - type: web
    name: leadnest-docs
    runtime: static
    branch: main
    buildCommand: |
      mkdir -p public
      cat > public/index.html << 'EOF'
      <!DOCTYPE html>
      <html>
      <head>
          <title>LeadNest API Documentation</title>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@4.15.5/swagger-ui.css" />
          <style>
            .swagger-ui .topbar { display: none; }
            .swagger-ui .info hgroup.main h2 { color: #3b82f6; }
          </style>
      </head>
      <body>
          <div id="swagger-ui"></div>
          <script src="https://unpkg.com/swagger-ui-dist@4.15.5/swagger-ui-bundle.js"></script>
          <script>
          SwaggerUIBundle({
              url: "https://leadnest-api.onrender.com/openapi.json",
              dom_id: "#swagger-ui",
              presets: [
                  SwaggerUIBundle.presets.apis,
                  SwaggerUIBundle.presets.standalone
              ],
              layout: "StandaloneLayout",
              deepLinking: true,
              showExtensions: true,
              showCommonExtensions: true
          });
          </script>
      </body>
      </html>
      EOF
    staticPublishPath: ./public
    domains:
      - leadnest-docs.onrender.com

databases:
  - name: leadnest-db
    databaseName: leadnest_prod
    user: leadnest_user
    plan: starter
    region: oregon
    postgresMajorVersion: 15
