# 🚀 LeadNest Backend Deployment Automation Script
# This script handles everything that can be automated locally

Write-Host "🚀 LeadNest Backend Deployment Setup" -ForegroundColor Cyan
Write-Host "=================================" -ForegroundColor Cyan

# Navigate to backend directory
Set-Location "c:\Users\mccab\contractornest\backend"

Write-Host "📁 Current directory: $(Get-Location)" -ForegroundColor Green

# Check git status
Write-Host "📊 Checking git status..." -ForegroundColor Yellow
git status

# Add render.yaml if not already added
Write-Host "📦 Adding render.yaml configuration..." -ForegroundColor Yellow
git add render.yaml

# Commit the render.yaml
Write-Host "💾 Committing render configuration..." -ForegroundColor Yellow
git commit -m "📦 Add Render.com deployment configuration - Ready for deployment"

# Display current remote
Write-Host "🌐 Current git remotes:" -ForegroundColor Yellow
git remote -v

Write-Host ""
Write-Host "✅ LOCAL SETUP COMPLETE!" -ForegroundColor Green
Write-Host ""
Write-Host "🔴 MANUAL STEPS REQUIRED:" -ForegroundColor Red
Write-Host "1. Go to https://github.com (login with useleadnest@gmail.com)" -ForegroundColor White
Write-Host "2. Create new repository: 'leadnest-backend'" -ForegroundColor White
Write-Host "3. Set as PUBLIC repository" -ForegroundColor White
Write-Host "4. Copy the repository URL (should be: https://github.com/useleadnest/leadnest-backend.git)" -ForegroundColor White
Write-Host ""
Write-Host "📋 THEN RUN THESE COMMANDS:" -ForegroundColor Magenta
Write-Host "git remote set-url origin https://github.com/useleadnest/leadnest-backend.git" -ForegroundColor White
Write-Host "git push -u origin main" -ForegroundColor White
Write-Host ""
Write-Host "🌐 RENDER DEPLOYMENT:" -ForegroundColor Blue
Write-Host "1. Go to https://render.com" -ForegroundColor White
Write-Host "2. Sign up with useleadnest@gmail.com" -ForegroundColor White
Write-Host "3. Connect GitHub account" -ForegroundColor White
Write-Host "4. Select 'leadnest-backend' repository" -ForegroundColor White
Write-Host "5. Render will auto-detect render.yaml" -ForegroundColor White
Write-Host "6. Add environment variables (see ENVIRONMENT_VARIABLES.md)" -ForegroundColor White
Write-Host ""

# Create environment variables reference
$envVars = @"
# 🔑 Environment Variables for Render Deployment

## Required Environment Variables
Add these in your Render dashboard:

### Database
- `DATABASE_URL` - Auto-generated by Render PostgreSQL addon

### Stripe Integration  
- `STRIPE_PUBLISHABLE_KEY` - Your Stripe publishable key
- `STRIPE_SECRET_KEY` - Your Stripe secret key  
- `STRIPE_WEBHOOK_SECRET` - Your Stripe webhook signing secret

### OpenAI Integration
- `OPENAI_API_KEY` - Your OpenAI API key

### Security
- `JWT_SECRET_KEY` - Auto-generated by Render

### Application Settings
- `FRONTEND_URL` - https://useleadnest.com
- `ENVIRONMENT` - production
- `CORS_ORIGINS` - https://useleadnest.com,https://www.useleadnest.com
- `LOG_LEVEL` - info

## How to Get Your API Keys:

### Stripe Keys:
1. Go to https://dashboard.stripe.com/apikeys
2. Copy your publishable key (starts with pk_)
3. Copy your secret key (starts with sk_)
4. For webhook secret: Go to Webhooks section, create endpoint for your Render URL

### OpenAI API Key:
1. Go to https://platform.openai.com/api-keys
2. Create new secret key
3. Copy the key (starts with sk-)

### After Deployment:
Your backend will be available at: https://your-app-name.onrender.com
Health check: https://your-app-name.onrender.com/health
"@

$envVars | Out-File -FilePath "ENVIRONMENT_VARIABLES.md" -Encoding UTF8

Write-Host "📄 Created ENVIRONMENT_VARIABLES.md with all required keys" -ForegroundColor Green
Write-Host ""
Write-Host "🎯 WHAT'S READY:" -ForegroundColor Green
Write-Host "✅ Backend code committed and ready" -ForegroundColor White
Write-Host "✅ Render.yaml configuration created" -ForegroundColor White  
Write-Host "✅ Environment variables documented" -ForegroundColor White
Write-Host "✅ Git repository initialized" -ForegroundColor White
Write-Host ""
Write-Host "⏳ WAITING FOR:" -ForegroundColor Yellow
Write-Host "🔴 GitHub repository creation (manual)" -ForegroundColor White
Write-Host "🔴 Git push to GitHub (after repo creation)" -ForegroundColor White
Write-Host "🔴 Render account setup (manual)" -ForegroundColor White
Write-Host "🔴 Environment variables configuration (manual)" -ForegroundColor White
