name: Backend • Build, Deploy (API), Smoke

# Alternative workflow using Render API instead of deploy hook
# To use this instead of the main backend.yml:
# 1. Rename backend.yml to backend-webhook.yml (to disable it)
# 2. Rename this file to backend.yml
# 3. Set these secrets: RENDER_API_KEY, RENDER_SERVICE_ID

on:
  push:
    branches: [ main, master ]
    paths:
      - "backend-flask/**"
      - ".github/workflows/backend-api.yml"
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-flask
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend-flask/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Lint (optional)
        run: |
          pip install flake8 || true
          flake8 . --max-line-length=120 --exclude=migrations || true

      - name: Unit tests (optional)
        run: |
          if [ -f tests/__init__.py ] || ls tests/*.py >/dev/null 2>&1; then
            pip install pytest
            pytest -q
          else
            echo "No backend tests found — skipping."
          fi

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render (Option B - API Method)
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          if [ -z "$RENDER_API_KEY" ] || [ -z "$RENDER_SERVICE_ID" ]; then
            echo "Warning: RENDER_API_KEY or RENDER_SERVICE_ID not set, skipping deploy"
            exit 0
          fi
          
          echo "Triggering Render deployment via API..."
          DEPLOY_RESPONSE=$(curl -fsS -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -d '{}')
          
          DEPLOY_ID=$(echo "$DEPLOY_RESPONSE" | jq -r '.id')
          echo "Deploy triggered with ID: $DEPLOY_ID"
          
          # Optional: Poll the deploy until live
          echo "Polling deploy status..."
          for i in {1..60}; do
            DEPLOY_STATUS=$(curl -fsS \
              -H "Authorization: Bearer $RENDER_API_KEY" \
              "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys/$DEPLOY_ID" | jq -r '.status')
            
            echo "Deploy $DEPLOY_ID status: $DEPLOY_STATUS (check $i/60)"
            
            if [ "$DEPLOY_STATUS" = "live" ]; then
              echo "✅ Deploy completed successfully!"
              break
            elif [ "$DEPLOY_STATUS" = "build_failed" ] || [ "$DEPLOY_STATUS" = "deploy_failed" ]; then
              echo "❌ Deploy failed with status: $DEPLOY_STATUS"
              exit 1
            fi
            
            sleep 10
          done

      - name: Wait for service health
        env:
          RENDER_BACKEND_BASE_URL: ${{ secrets.RENDER_BACKEND_BASE_URL }}
        run: |
          if [ -z "$RENDER_BACKEND_BASE_URL" ]; then
            echo "RENDER_BACKEND_BASE_URL not set, skipping health check"
            exit 0
          fi
          
          echo "Waiting for service to be healthy..."
          for i in {1..30}; do
            if curl -fsS "$RENDER_BACKEND_BASE_URL/readyz" >/dev/null 2>&1; then
              echo "Service is healthy!"
              break
            fi
            echo "Attempt $i/30: Service not ready, waiting 10s..."
            sleep 10
          done

  smoke:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for smoke test scripts)
        uses: actions/checkout@v4

      - name: Install dependencies for smoke tests
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: Run comprehensive Bash smoke tests
        env:
          BASE_URL: ${{ secrets.RENDER_BACKEND_BASE_URL }}
          SMOKE_EMAIL: ${{ secrets.SMOKE_EMAIL }}
          SMOKE_PASSWORD: ${{ secrets.SMOKE_PASSWORD }}
        run: |
          if [ -z "$BASE_URL" ]; then
            echo "RENDER_BACKEND_BASE_URL not set, skipping comprehensive smoke test"
            exit 0
          fi
          
          echo "Running comprehensive smoke test suite..."
          chmod +x test-leadnest.sh
          ./test-leadnest.sh "$BASE_URL" "${SMOKE_EMAIL:-a@b.c}" "${SMOKE_PASSWORD:-x}" --skip-large-csv

      - name: Upload smoke test JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-smoke-junit-api
          path: |
            test-leadnest.xml
            Test-LeadNest.xml
          if-no-files-found: ignore
